title: franco hielpos
description: >- # this means to ignore newlines until "baseurl:"
   Argentinian technology lover and sysadmin looking to get into the SRE world. Passionate about Kubernetes. Certified Kubernetes Administrator. I write (some little) code.
   This is just a random blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "fhielpos.github.io"
github_username:  fhielpos
permalink: /:title:output_ext
author: Franco
# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jemoji
  - jekyll-feed
